# This is a basic workflow to help you get started with Actions

name: Cloud hpo-web api deploy

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  load:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checking out repository"
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: "Set hpo release version"
        run: echo "HPO_RELEASE_VERSION=$(grep "version" server/build.gradle | tr '"' ' ' | sed -n -e 's/version  //p' | xargs)" >> $GITHUB_ENV

      - name: "Set gcp public bucket location"
        run: echo "HPO_RELEASE_PUBLIC_GCP_LOCATION=gs://jax-robinson-hpo-01-public-bucket/" >> $GITHUB_ENV

      - name: "Generate our service artifact"
        run: ./gradlew prepareDocker

      - name: "Docker build image"
        run: |
          docker build -t us-east1-docker.pkg.dev/jax-robinson-hpo-01/hpo-docker-repo/hpo-api:$HPO_RELEASE_VERSION server/build/docker
      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: "Docker configure Artifact Registry"
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
      # Push image to Artifact Registry
      - name: Build
        run: |-
          docker push us-east1-docker.pkg.dev/jax-robinson-hpo-01/hpo-docker-repo/hpo-api:$HPO_RELEASE_VERSION
      # Redeploy cloud run instance
