# This is a basic workflow to help you get started with Actions

name: Cloud Sql Deploy

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  load:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: hpo_web
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: "Set hpo release version"
        run: echo "HPO_RELEASE_VERSION=$(grep "version" server/build.gradle | tr '"' ' ' | sed -n -e 's/version  //p' | xargs)" >> $GITHUB_ENV
      - name: "Set hpo sql file name"
        run: echo "HPO_RELEASE_SQL_FILENAME=hpo_web-$HPO_RELEASE_VERSION.sql" >> $GITHUB_ENV
      - name: "Set gcp sql location"
        run: echo "HPO_RELEASE_SQL_GCP_LOCATION=gs://jax-robinson-hpo-01-project-data/$HPO_RELEASE_SQL_FILENAME" >> $GITHUB_ENV
      - name: Load our database with the new data
        run: ./gradlew runCommand -Dgrails.env="gcp" -Pargs="load-hpo-db"

      - name: Export our database to a sql file
        run: |
          mysqldump --column-statistics=0 -h 127.0.0.1 -u root --password=password --opt hpo_web > $HPO_RELEASE_SQL_FILENAME

      - name: Copy sql file to gcp bucket
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: jax-robinson-hpo-01
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: cp $HPO_RELEASE_SQL_FILENAME gs://jax-robinson-hpo-01-project-data/
          cli: gsutil
      - name: gcloud import cloud sql database
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: jax-robinson-hpo-01
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: sql import sql hpo-web $HPO_RELEASE_SQL_GCP_LOCATION --database=hpo -q
          cli: gcloud
