name: Cloud hpo-web client deploy

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  load:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checking out repository"
        uses: actions/checkout@v3
      - name: "Seting up node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: "Set hpo release version"
        run: echo "HPO_RELEASE_VERSION=$(cat ./package.json | grep -m 1 version | sed 's/[^0-9.]//g')" >> $GITHUB_ENV
      - name: "Set gcp public bucket location"
        run: echo "HPO_RELEASE_PUBLIC_GCP_LOCATION=gs://jax-robinson-hpo-01-public-bucket" >> $GITHUB_ENV
      - name: "Set gcp client backup location"
        run: echo "HPO_CLIENT_BACKUP_GCP_LOCATION=gs://jax-robinson-hpo-01-project-data/client-backup/$HPO_RELEASE_VERSION" >> $GITHUB_ENV
      - name: "Generate and upload our client sources"
        run: |
          cd client
          npm install
          npm run buildProd
          # Force update our backup file and copy to new backup
          gsutil -m rm $HPO_CLIENT_BACKUP_GCP_LOCATION/* 2> /dev/null || true
          gsutil cp -r dist/* $HPO_CLIENT_BACKUP_GCP_LOCATION/
          # Update our public site with the most recent version
          gsutil -m rm $HPO_RELEASE_PUBLIC_GCP_LOCATION/* 2> /dev/null || true
          gsutil cp -r $HPO_CLIENT_BACKUP_GCP_LOCATION/* $HPO_RELEASE_PUBLIC_GCP_LOCATION/
