grails:
  profile: 'angular'
  resources:
    pattern: /**
  mime:
    disable:
      accept:
        header:
          userAgents: [
            'Gecko',
            'WebKit',
            'Presto',
            'Trident'
          ]
    types:
      json: [
        'application/json',
        'text/json'
      ]
      hal: [
        'application/hal+json',
        'application/hal+xml'
      ]
      xml: [
        'text/xml',
        'application/xml'
      ]
      atom: 'application/atom+xml'
      css: 'text/css'
      csv: 'text/csv'
      js: 'text/javascript'
      rss: 'application/rss+xml'
      text: 'text/plain'
      all: '*/*'
  cors:
    enabled: true
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
    groovy:
        template:
            check-template-location: false
#    config:
#      import:  ${HOME}/.grails/hpo_web/application.yml
    devtools:
      restart:
        enabled: false

management:
  enabled-by-default: true

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

logging:
  level:
    root: ERROR
    hpo: DEBUG

dataSource:
  initialSize: 5
  maxActive: 50
  minIdle: 5
  maxIdle: 25
  maxWait: 10000
  maxAge: 10 * 60000
  timeBetweenEvictionRunsMillis: 5000
  minEvictableIdleTimeMillis: 60000
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3
  validationInterval: 15000
  testOnBorrow: true
  testWhileIdle: true
  testOnReturn: false
  driverClassName: "com.mysql.jdbc.Driver"

environments:
  development:
    dataSource:
      pooled: true
      dbCreate: "update"
      url: "jdbc:mysql://localhost:3306/hpo_web?autoReconnect=true"
      username: "root"
      password: "password"
  test:
    dataSource:
      pooled: true
      dbCreate: "update"
      url: "jdbc:mysql://localhost:3306/hpo_web?autoReconnect=true"
      username: ${HPO_MYSQL_USERNAME}
      password: ${HPO_MYSQL_PASSWORD}
  gcp:
    dataSource:
      dbCreate: "update"
      url: "jdbc:mysql://localhost:3306/hpo_web"
      username: "root"
      password: "password"
  production:
    dataSource:
     pooled: true
     dbCreate: "update"
     url: "jdbc:mysql://localhost:3306/hpo_web?autoReconnect=true"
     username: ${HPO_MYSQL_USERNAME}
     password: ${HPO_MYSQL_PASSWORD}



