grails:
  profile: 'angular'
  resources:
    pattern: /**
  mime:
    disable:
      accept:
        header:
          userAgents: [
            'Gecko',
            'WebKit',
            'Presto',
            'Trident'
          ]
    types:
      json: [
        'application/json',
        'text/json'
      ]
      hal: [
        'application/hal+json',
        'application/hal+xml'
      ]
      xml: [
        'text/xml',
        'application/xml'
      ]
      atom: 'application/atom+xml'
      css: 'text/css'
      csv: 'text/csv'
      js: 'text/javascript'
      rss: 'application/rss+xml'
      text: 'text/plain'
      all: '*/*'


  urlmapping:
    cache:
      maxsize: 1000

  cors:
    enabled: true
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
    groovy:
        template:
            check-template-location: false
    config:
      import:  ${HOME}/.grails/hpo_web/application.yml

management:
  endpoints:
    enabled-by-default: true

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
