grails:
  profile: 'angular'
  resources:
    pattern: /**
  mime:
    disable:
      accept:
        header:
          userAgents: [
            'Gecko',
            'WebKit',
            'Presto',
            'Trident'
          ]
    types:
      json: [
        'application/json',
        'text/json'
      ]
      hal: [
        'application/hal+json',
        'application/hal+xml'
      ]
      xml: [
        'text/xml',
        'application/xml'
      ]
      atom: 'application/atom+xml'
      css: 'text/css'
      csv: 'text/csv'
      js: 'text/javascript'
      rss: 'application/rss+xml'
      text: 'text/plain'
      all: '*/*'


  urlmapping:
    cache:
      maxsize: 1000

  cors:
    enabled: true

  #plugin
  #console
  #csrfProtection
  #enabled = false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
    groovy:
        template:
            check-template-location: false
    config:
      import:  /Users/gargam/.grails/hpo_web/application.yml

management:
  endpoints:
    enabled-by-default: true

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

#environments:
#    development:
#        dataSource:
#          dbCreate: 'update'
#          url: "jdbc:h2:./build/devDb;IGNORECASE=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
#          grails.dbconsole.enabled: true
#          grails.dbconsole.urlRoot: '/admin/dbconsole'
#    test:
#        dataSource:
#          dbCreate: 'update'
#          url: "jdbc:h2:./build/testDb;IGNORECASE=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
#          grails.dbconsole.enabled: true
#          grails.dbconsole.urlRoot: '/admin/dbconsole'
#    production:
#        dataSource:
#            dbCreate: 'none'
#            url: 'jdbc:h2:$externalConfigDir/prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
#            properties:
#                jmxEnabled: true
#                initialSize: 5
#                maxActive: 50
#                minIdle: 5
#                maxIdle: 25
#                maxWait: 10000
#                maxAge: 600000
#                timeBetweenEvictionRunsMillis: 5000
#                minEvictableIdleTimeMillis: 60000
#                validationQuery: 'SELECT 1'
#                validationQueryTimeout: 3
#                validationInterval: 15000
#                testOnBorrow: true
#                testWhileIdle: true
#                testOnReturn: false
#                jdbcInterceptors: 'ConnectionState'
#                defaultTransactionIsolation: 2




